<el-table-column
        prop="name"
        label="仓库名称"
>
</el-table-column>
<el-table-column
        prop="type.name"
        label="仓库类型"
>
</el-table-column>
<el-table-column
        prop="inventories_count"
        label="库存总计"
>
</el-table-column>
