
<el-table-column
        prop="type_name"
        label="订单来源"
>
</el-table-column>
<el-table-column
        prop="price"
        label="订单总价"
>
</el-table-column>
<el-table-column
        prop="market.name"
        label="渠道"
>
</el-table-column>
<el-table-column
        prop="current_state"
        label="状态"
>
</el-table-column>